apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: guinea-pig
  labels:
    team: iac
spec:
  selector:
    matchLabels:
      app: guinea-pig
  endpoints:
  - interval: 30s
    port: web